#include <stdio.h>
#include <unistd.h>
#include <stdbool.h>

/* This file is a brute-force result tester (opens results generated by the file
 * lab8_zad1-development2 and reads a file line by line comparing each S, X pair
 * generated by the algorithm from such a program with its brute-force calculated
 * equivalent (when a X result is -1) or checks whether X can sum up to S
 * */


typedef unsigned long long llu;
typedef long long ll;

bool check(llu S, ll X);


llu low = 0;

int main() {
    llu n, m, step;
    n = 0;
    m = 1000000;
    step = 1000;
    FILE *fp;

    chdir("F:\\Edukacja\\Studia\\2. semestr\\Programowanie Imperatywne\\Laboratoria\\8. Laboratorium\\Zadanie1");

    fp = fopen("results.txt", "r");

    if (fp == NULL){
        printf("Error Opening File\n");
        exit (0);
    }

    llu S;
    ll X;
    for (llu i = n; i <= m; i++) {
        fscanf(fp, "%I64d %I64d\n", &S, &X);
        if (!(i % step)) printf("\nTested sum: S=%I64d\n", S);
        if (check(S, X)) continue;
        else printf("WRONG! For sum: %I64d  Got: %I64d\n", S, X);
    }

    fclose(fp);

    return 0;
}

// Check if an X is a correct result for S
bool check(llu S, ll X) {
    llu total;
    if (X == -1) {
        if (S == 0) return true;
        if (S >= 100) {
            llu new_low = low > 0 ? low : 91;
            do {
                low = new_low;
                new_low = (low - 1) * 10 + 1;
            } while (new_low < S);
        }
        llu j;
        for (llu i = low; i <= S; i++) {
            total = 0;
            j = i;
            while (j) {
                total += j;
                j /= 10;
            }
            if (total == S) return false;
        }
        return true;
    } else {
        total = 0;
        while (X) {
            total += (llu)X;
            X /= 10;
        }
        return total == S;
    }
}
